export type Belt =
  | "White"
  | "Yellow"
  | "Orange"
  | "Green"
  | "Blue"
  | "Purple"
  | "Brown"
  | "Red"
  | "Black"
  | "Unranked";

export type LockRecord = {
  id: string;
  name: string;
  version?: string;
  mechanisms: string[];
  belt: Belt;
  beltLevel?: `Black ${1 | 2 | 3 | 4 | 5}`;
  status: "Owned" | "Wishlist";
  picked: boolean;
};

export const profileSnapshotDate = "September 2, 2026 · 10:41 PM EDT";

export const beltOrder: Belt[] = [
  "White",
  "Yellow",
  "Orange",
  "Green",
  "Blue",
  "Purple",
  "Brown",
  "Red",
  "Black",
  "Unranked",
];

export const beltColors: Record<Belt, string> = {
  White: "#f4f6fa",
  Yellow: "#f4db32",
  Orange: "#ff8a34",
  Green: "#34a853",
  Blue: "#3b82f6",
  Purple: "#a855f7",
  Brown: "#7b4729",
  Red: "#ef4444",
  Black: "#080a0f",
  Unranked: "#566171",
};

export const profileBeltCounts: Record<Belt, number> = {
  White: 3,
  Yellow: 5,
  Orange: 8,
  Green: 16,
  Blue: 35,
  Purple: 24,
  Brown: 14,
  Red: 12,
  Black: 29,
  Unranked: 1,
};

export const statusBenchmarks = [
  { label: "Owned", user: 78, average: 14, topTen: 250 },
  { label: "Picked", user: 11, average: 11, topTen: 280 },
  { label: "Recorded", user: 0, average: 11, topTen: 260 },
  { label: "Wishlist", user: 69, average: 8, topTen: 100 },
];

export const progression = [
  { belt: "Yellow" as Belt, date: "2024-09-02" },
  { belt: "Orange" as Belt, date: "2024-09-27" },
  { belt: "Green" as Belt, date: "2025-05-18" },
  { belt: "Blue" as Belt, date: "2025-05-19" },
];

const lockCatalog: Omit<LockRecord, "status" | "picked">[] = [
  {
    id: "07034c0f",
    name: "Any Acrylic Padlock",
    mechanisms: ["Various"],
    belt: "White",
  },
  {
    id: "901b35b2",
    name: "Any Cutaway Lock",
    mechanisms: ["Various"],
    belt: "White",
  },
  {
    id: "562e964e",
    name: "Master Lock #3",
    mechanisms: ["Pin-tumbler"],
    belt: "White",
  },
  {
    id: "d974b48f",
    name: "Brinks 164 padlock",
    mechanisms: ["Pin-tumbler"],
    belt: "Yellow",
  },
  {
    id: "58307da0",
    name: "Brinks Brass Padlocks",
    mechanisms: ["Pin-tumbler"],
    belt: "Yellow",
  },
  {
    id: "2455f0ae",
    name: "Master Lock 140 Series / Master Lock 9140 EURD",
    version: "Ex: 140, 141, 142, etc.",
    mechanisms: ["Pin-tumbler"],
    belt: "Yellow",
  },
  {
    id: "40f7d7c7",
    name: "Schlage Original Commercial/Residential",
    mechanisms: ["Pin-tumbler"],
    belt: "Yellow",
  },
  {
    id: "a460c971",
    name: "Squire 440",
    version: "4 lever, pin key",
    mechanisms: ["Lever"],
    belt: "Yellow",
  },
  {
    id: "632f4069",
    name: "ABUS 55/40",
    version: "40mm or larger",
    mechanisms: ["Pin-tumbler"],
    belt: "Orange",
  },
  {
    id: "bf8970de",
    name: "ACE Tubular",
    mechanisms: ["Pump/push"],
    belt: "Orange",
  },
  {
    id: "171f76e9",
    name: "Burg Wächter Boccia",
    mechanisms: ["Dimple"],
    belt: "Orange",
  },
  {
    id: "efc01233",
    name: "Master Lock 150 / Master Lock 160 / Master Lock 9150 EURD",
    mechanisms: ["Pin-tumbler"],
    belt: "Orange",
  },
  {
    id: "8d67f9b7",
    name: 'Master Lock 1921D "100 Anniversary" Padlock',
    mechanisms: ["Pin-tumbler"],
    belt: "Orange",
  },
  {
    id: "9ca2c109",
    name: "Master Lock 570 / Master Lock 575 / Master Lock 576",
    mechanisms: ["Pin-tumbler"],
    belt: "Orange",
  },
  {
    id: "ea1d1d8c",
    name: "Schlage Everest",
    mechanisms: ["Pin-tumbler"],
    belt: "Orange",
  },
  {
    id: "222bd1fa",
    name: "Yale 112",
    mechanisms: ["Disc detainer"],
    belt: "Orange",
  },
  {
    id: "74a00ae3",
    name: "ABUS 72/40 / ABUS 34CS55 Platinum",
    version: "Guttable version",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "e1625c4d",
    name: "ABUS 80TI Titalium",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "2484ce70",
    name: "ABUS EC 75/30 / ABUS 34/55 Strada",
    mechanisms: ["Dimple"],
    belt: "Green",
  },
  {
    id: "13b06cba",
    name: "ABUS GDS",
    version: "with trees and tapered pins",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "2ae1e0b8",
    name: "American Lock 1100 / A1100",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "1ae40987",
    name: "American Lock 1160",
    version: "1100 but with 6 pin stacks",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "5a6170fb",
    name: "American Lock S1100",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "0b82681f",
    name: "ASSA 500 / Ruko 500",
    version: "tapered drivers",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "e957e0d6",
    name: "Brady SafeKey",
    mechanisms: ["Pump/push"],
    belt: "Green",
  },
  {
    id: "73a718cb",
    name: "Corbin Russwin Master Ring",
    version: "**",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "cd0c2ff9",
    name: "FAB 200RS",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "639c4f0b",
    name: "FJM Padlock",
    mechanisms: ["Disc detainer"],
    belt: "Green",
  },
  {
    id: "c942490e",
    name: "Master Lock 410 LOTO (Lockout Tagout)",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "366d5f50",
    name: "Master Lock 6835",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "37951bc4",
    name: "Yale 500+",
    version: "without overmilling",
    mechanisms: ["Pin-tumbler"],
    belt: "Green",
  },
  {
    id: "4f6bcdb7",
    name: "Zarker J45/J45S",
    mechanisms: ["Disc detainer"],
    belt: "Green",
  },
  {
    id: "c6529d9c",
    name: "Any SFIC format lock",
    version: "**",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "85d93eb1",
    name: "ABUS C73 / ABUS C83 / ABUS C90",
    version: "new pinning: security keypins + serrated and spooled t-pins",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "5c0d870b",
    name: "ABUS E20 / ABUS E30 / ABUS E60 / ABUS E70 / ABUS NP (6-pin)",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "9ec8706c",
    name: "ABUS EC 75/50 / ABUS 75IB/50",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "d9e3829f",
    name: "ASSA 500 / ASSA Flexcore/Flexcore Plus",
    version: "5 pin with barrels and matched countermilling",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "b89d9e11",
    name: "ASSA 500 / Ruko 500",
    version: "with barrel drivers, no countermilling",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "d08aa492",
    name: "ASSA 700",
    version: "7 pin with spools and no countermilling",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "f1e92541",
    name: "ASSA 700",
    version: "7 pin with tapered drivers",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "1bee7a66",
    name: "ASSA R502",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "111062fc",
    name: "Bison/HYT/Lays/Qlsy Chain Key Lock",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "32fa52a6",
    name: "Burg Wächter Diamant",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "5b842c0e",
    name: "Chubb Cruiser",
    version: "5 lever",
    mechanisms: ["Lever"],
    belt: "Blue",
  },
  {
    id: "1add3dd0",
    name: "Cobra C3 Sidewinder",
    mechanisms: ["Slider"],
    belt: "Blue",
  },
  {
    id: "aee424c0",
    name: "FAB 3* Profi / FAB 4* Profi",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "2801996f",
    name: "GEGE AP1000 / GEGE AP2000 / GEGE AP3000",
    version: "5 pins",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "aa7fc00e",
    name: 'Gege pExtra / Alfa "pExtra"',
    version: "5 pin",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "959a6b9d",
    name: "GOAL S",
    version: "5 pins",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "9b94b1c0",
    name: "iNAHO Tierkey",
    version: "3 row, short format",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "ebcb29b9",
    name: "Ingersoll 6 Lever Padlock",
    mechanisms: ["Lever"],
    belt: "Blue",
  },
  {
    id: "40e50dd4",
    name: "Kaken KX3",
    version: "exterior, <6 sliders/wafers",
    mechanisms: ["Pin-tumbler", "Slider", "Wafer"],
    belt: "Blue",
  },
  {
    id: "ab9df828",
    name: "Kawaha Kawaha / Magmaus Magmaus",
    mechanisms: ["Disc detainer"],
    belt: "Blue",
  },
  {
    id: "331c9d36",
    name: "Lockwood 334B45 / Lockwood 356S63 / Lockwood 214A40 / Lockwood 215A40 / Lockwood 270S70",
    version: "with spools",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "c0af329b",
    name: "Mindy Pagoda (round key)",
    mechanisms: ["Pump/push"],
    belt: "Blue",
  },
  {
    id: "0418a174",
    name: "Mul-T-Lock Classic",
    version: "standard drivers",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "aec0c82d",
    name: "Mul-T-Lock Classic / Mul-T-Lock Interactive",
    version: "4 pins, 4 spooled drivers",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "a0ec1618",
    name: "Mul-T-Lock Classic / Mul-T-Lock Interactive",
    version: "5 pins, 3 or fewer spooled drivers",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "6e0bfdd2",
    name: "Mul-T-Lock Integrator",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "1d80c9bb",
    name: "Omellow R3",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "fb5a9eb7",
    name: "PACLOCK 90A Pro",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "37dc53bb",
    name: "SEGA Cam Lock",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "b0d2e04c",
    name: "Takigen 10-pin / Takigen C288",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "35330d19",
    name: "Tokoz Tech",
    mechanisms: ["Pin-tumbler", "Wafer"],
    belt: "Blue",
  },
  {
    id: "55511995",
    name: "TrioVing 508 / Ving Vingcard 55##",
    version: "with trampoline pins",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "779e7dcb",
    name: "Yale 500 / Yale B",
    mechanisms: ["Pin-tumbler"],
    belt: "Blue",
  },
  {
    id: "5e3397a9",
    name: "Zeta Padlock",
    version: "Models: ZR45, ZR55, ZU55",
    mechanisms: ["Dimple"],
    belt: "Blue",
  },
  {
    id: "c8259a23",
    name: "Any SFIC format lock (unless otherwise specified)",
    version: "**",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "dd1dd313",
    name: "ABUS XP1 / ABUS TS5000",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "ef221c67",
    name: "ASSA 500 / Ruko 500",
    version: "5 pin stacks, gin drivers and matching sleeve",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "45e3cde7",
    name: "ASSA 600 / ASSA Max+ Restricted / Ruko 600",
    version: "Barrel spools and matching countermilling",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "122b5621",
    name: "ASSA Guideline",
    version: "6 pin with active side pins",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Purple",
  },
  {
    id: "f3666121",
    name: "Avocet ABS / ERA Professional Cylinder / Federal Lock U-systems (UCF/UCH/UCS/UUS)-3100 / Thirard Federal S / Thirard Federal 2",
    mechanisms: ["Dimple", "Magnet"],
    belt: "Purple",
  },
  {
    id: "ed9fa926",
    name: "Burg Wächter Gamma 700",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "1f3a8ff9",
    name: "Chubb Battleship",
    version: "6 lever, offset key",
    mechanisms: ["Lever"],
    belt: "Purple",
  },
  {
    id: "71bce5b7",
    name: "Corbin Russwin Emhart",
    version: "4 pins **",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "e8901d1c",
    name: 'Eagle "Supr-Security"',
    version: "without shutter",
    mechanisms: ["Wafer"],
    belt: "Purple",
  },
  {
    id: "8c2983b5",
    name: "EVVA DPI / EVVA DPS / EVVA DPX / EVVA EPS",
    version: "slider version",
    mechanisms: ["Slider"],
    belt: "Purple",
  },
  {
    id: "3fbd7b3d",
    name: "Godrej Ultra",
    version: "14 pins in 3 rows",
    mechanisms: ["Dimple"],
    belt: "Purple",
  },
  {
    id: "07bc680a",
    name: "Illinois Duo",
    mechanisms: ["Wafer"],
    belt: "Purple",
  },
  {
    id: "c11aca1a",
    name: "Ingersoll 10 lever padlock",
    mechanisms: ["Lever/sidebar"],
    belt: "Purple",
  },
  {
    id: "9982c0eb",
    name: "Lockman Megacross",
    version: "9-pins, mushroom drivers",
    mechanisms: ["Dimple"],
    belt: "Purple",
  },
  {
    id: "71833308",
    name: "Lockwood Twin",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Purple",
  },
  {
    id: "8f7f1830",
    name: "Master Lock #19",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "aeaa6a09",
    name: "Medeco Original Camlock",
    version: "≥ 5 pins ******",
    mechanisms: ["Slider", "Sidebar"],
    belt: "Purple",
  },
  {
    id: "826c31e0",
    name: "Medeco Original / Medeco Biaxial / Medeco M3 / Chubb Biaxial",
    version: "≥ 5 pins ******",
    mechanisms: ["Sidebar", "Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "06a28ac7",
    name: "Mindy Pagoda AF 16-50",
    version: "flat key",
    mechanisms: ["Pump/push"],
    belt: "Purple",
  },
  {
    id: "3335df97",
    name: "Mul-T-Lock Jr / Mul-T-Lock Classic / Mul-T-Lock Interactive",
    version: "5 pin stacks, ≥ 4 spooled drivers",
    mechanisms: ["Dimple"],
    belt: "Purple",
  },
  {
    id: "6d754a0a",
    name: "Rielda rekeyable lock",
    mechanisms: ["Pin-tumbler"],
    belt: "Purple",
  },
  {
    id: "3dabf132",
    name: "Schlage Everest 29SL",
    mechanisms: ["Slider"],
    belt: "Purple",
  },
  {
    id: "1be10736",
    name: "Yale 5000",
    mechanisms: ["Pin-tumbler", "Slider"],
    belt: "Purple",
  },
  {
    id: "b13f4b57",
    name: "Any SFIC with security pins",
    version: "**",
    mechanisms: ["Pin-tumbler"],
    belt: "Brown",
  },
  {
    id: "da09d849",
    name: "Abloy Classic",
    mechanisms: ["Disc detainer"],
    belt: "Brown",
  },
  {
    id: "b8350900",
    name: "ABUS Plus",
    version: "no butterfly discs",
    mechanisms: ["Disc detainer"],
    belt: "Brown",
  },
  {
    id: "d3ad5a73",
    name: "ASSA d12 / ASSA P600 / ASSA Neptun 1900 / Ruko Merkur / TrioVing d12 level 1 / Ruko 1200",
    version: "barrel drivers, forked keypins, optional long pin",
    mechanisms: ["Pin-tumbler"],
    belt: "Brown",
  },
  {
    id: "1459e2c6",
    name: "ASSA Desmo",
    version: "8 sliders, no mastered pins",
    mechanisms: ["Slider"],
    belt: "Brown",
  },
  {
    id: "e38d015b",
    name: "Burg Wächter Alpha 800",
    mechanisms: ["Wafer"],
    belt: "Brown",
  },
  {
    id: "9c627ebd",
    name: "Fichet 666",
    mechanisms: ["Slider"],
    belt: "Brown",
  },
  {
    id: "86e86a1d",
    name: "FTH Thirard Cobra",
    mechanisms: ["Pump/push"],
    belt: "Brown",
  },
  {
    id: "a1233156",
    name: "GOAL P",
    version: "6 pin",
    mechanisms: ["Pin-tumbler"],
    belt: "Brown",
  },
  {
    id: "ea1afad0",
    name: "Schlage Primus / Schlage Everest Primus",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Brown",
  },
  {
    id: "626da374",
    name: "Scorpion CX-5 / Marks High Security Lock",
    mechanisms: ["Pin-tumbler", "Slider"],
    belt: "Brown",
  },
  {
    id: "506b242a",
    name: "Van Lock",
    mechanisms: ["Pump/push"],
    belt: "Brown",
  },
  {
    id: "dd764207",
    name: "VSR 3-row",
    mechanisms: ["Dimple"],
    belt: "Brown",
  },
  {
    id: "93e4cf5f",
    name: "Walsall Locks 2000",
    version: "5 lever",
    mechanisms: ["Lever"],
    belt: "Brown",
  },
  {
    id: "b8350901",
    name: "ABUS Plus",
    version: "with butterfly discs",
    mechanisms: ["Disc detainer"],
    belt: "Red",
  },
  {
    id: "29ab2852",
    name: "ASSA 600 / Ruko 600",
    version: "6 pin, with gin spools and matched countermilling",
    mechanisms: ["Pin-tumbler"],
    belt: "Red",
  },
  {
    id: "75fb1e5c",
    name: "ASSA dp2400 / ASSA dp10 / TrioVing System 10 / Ruko DP2",
    version: "6 pin 4 slider",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Red",
  },
  {
    id: "3af2407a",
    name: "BKS Janus",
    version: "< 13 pins",
    mechanisms: ["Dimple"],
    belt: "Red",
  },
  {
    id: "9f613c4a",
    name: "GOAL V18 / GOAL GP",
    version: "<14 pins",
    mechanisms: ["Dimple"],
    belt: "Red",
  },
  {
    id: "281aa393",
    name: "Kromer Novum",
    mechanisms: ["Lever"],
    belt: "Red",
  },
  {
    id: "814c5368",
    name: "MIWA LS7",
    mechanisms: ["Slider"],
    belt: "Red",
  },
  {
    id: "9da7a5f2",
    name: "Robur 2391 Safe Deposit Lock",
    version: "barrels ≥ 3 chambers with matched milling",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Red",
  },
  {
    id: "112d0034",
    name: "Robur 2391 Safe Deposit Lock",
    version: "gins ≥ 3 chambers with matched milling",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Red",
  },
  {
    id: "4a7db3c6",
    name: "Rosengrens 32A / Rosengrens 32A8",
    version: "thin round center posts, few or no False gates",
    mechanisms: ["Disc detainer"],
    belt: "Red",
  },
  {
    id: "2ff8a738",
    name: "S&G 4440 series",
    mechanisms: ["Lever"],
    belt: "Red",
  },
  {
    id: "cf76cfde",
    name: "Schlage Everest 29 SL Primus XP",
    mechanisms: ["Slider", "Sidepins"],
    belt: "Red",
  },
  {
    id: "e87f0ca2",
    name: "Abloy Protec2",
    mechanisms: ["Disc detainer"],
    belt: "Black",
    beltLevel: "Black 3",
  },
  {
    id: "2ae6a691",
    name: "Abloy Sentry",
    mechanisms: ["Disc detainer"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "f133510b",
    name: "ASSA 700",
    version: "gin/tree pins and matching countermilling in ≥ 4 chambers, ≥ 2 tree pins",
    mechanisms: ["Pin-tumbler"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "104776ef",
    name: "ASSA Twin 6000",
    version: "gin drivers, 6 stacks with 5 side pins",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Black",
    beltLevel: "Black 2",
  },
  {
    id: "7168d463",
    name: "ASSA Twin Combi / ASSA Triton / ASSA Neptun 4900 / TrioVing Twin Control",
    version: "6 pin with 5 finger pins",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Black",
    beltLevel: "Black 2",
  },
  {
    id: "55053299",
    name: "ASSA Twin Exclusive / ASSA Twin 6000",
    version: "6 barrel drivers, 5 side pins",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "3f73d2ce",
    name: "ASSA Twin Maximum / ASSA Twin Pro / ASSA Twin v10 / ASSA Twin 2 / ASSA Twin Global",
    version: "barrel driver, 6 stacks with 5 side pins",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "ab1e901f",
    name: "Australian Lock Co. BiLock",
    version: "12 sliders, 0 mastered",
    mechanisms: ["Slider"],
    belt: "Black",
    beltLevel: "Black 2",
  },
  {
    id: "c6a14e93",
    name: "CAWI 7113 / CAWI 7123",
    mechanisms: ["Wafer"],
    belt: "Black",
    beltLevel: "Black 3",
  },
  {
    id: "2db935ea",
    name: 'Chubb "Definitive"',
    version: "jewelry box (steel comb leaf spring, pin or pipe key)",
    mechanisms: ["Lever"],
    belt: "Black",
    beltLevel: "Black 4",
  },
  {
    id: "3c73c705",
    name: "DOM ix Twinstar",
    mechanisms: ["Dimple"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "f7452b9f",
    name: "EVVA 3KS / EVVA 3KS+",
    version: "false gates and no mastered sliders",
    mechanisms: ["Slider"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "340154fa",
    name: "Fichet 450 / Fichet 484",
    version: "w/ False gates, 0 mastered levers",
    mechanisms: ["Lever/sidebar"],
    belt: "Black",
    beltLevel: "Black 2",
  },
  {
    id: "3ca098da",
    name: "GOAL Grand V",
    mechanisms: ["Dimple"],
    belt: "Black",
    beltLevel: "Black 3",
  },
  {
    id: "5103e650",
    name: "GOAL Z",
    version: "< 2 standard drivers",
    mechanisms: ["Pin-tumbler"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "f87db705",
    name: "Kromer Protector (BP55K)",
    mechanisms: ["Wafer"],
    belt: "Black",
    beltLevel: "Black 5",
  },
  {
    id: "f1857cef",
    name: "Lockman Megacross",
    version: "with pyramid drivers",
    mechanisms: ["Dimple"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "d1272b9f",
    name: "MIWA U9",
    version: "9 unmastered elements, barred False gates (old shallow False gates counts as BB1)",
    mechanisms: ["Lever/sidebar"],
    belt: "Black",
    beltLevel: "Black 2",
  },
  {
    id: "ccdbffbf",
    name: "MIWA WR",
    mechanisms: ["Slider"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "649eaebc",
    name: "Mul-T-Lock MT5+ / Mul-T-Lock 800 / Lockwood MT5 / IKON R10",
    version: "not mastered",
    mechanisms: ["Dimple", "Slider"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "f29a212f",
    name: "NATO Mersey",
    version: "14 lever",
    mechanisms: ["Lever"],
    belt: "Black",
    beltLevel: "Black 5",
  },
  {
    id: "6c0ec943",
    name: "Opnus Memolis",
    mechanisms: ["Lever/sidebar"],
    belt: "Black",
    beltLevel: "Black 4",
  },
  {
    id: "5cba063b",
    name: "Robur Disc Detainer Safe Deposit Lock",
    mechanisms: ["Disc detainer"],
    belt: "Black",
    beltLevel: "Black 2",
  },
  {
    id: "63a9a2b1",
    name: "Ruko Combi 2 / Ruko Garant 10 / FAB Variant",
    version: "6 pin with 5 finger pins",
    mechanisms: ["Pin-tumbler", "Sidepins"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "00cf7717",
    name: "Sargent Keso",
    mechanisms: ["Dimple"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "3198fffc",
    name: "Tokoz Pro",
    mechanisms: ["Disc detainer"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "e4bb0668",
    name: "UrbanAlps Stealth Key SK1",
    mechanisms: ["Lever/sidebar"],
    belt: "Black",
    beltLevel: "Black 1",
  },
  {
    id: "e718b140",
    name: "Western Electric 30B",
    mechanisms: ["Lever"],
    belt: "Black",
    beltLevel: "Black 5",
  },
  {
    id: "5a4310d5",
    name: "Western Electric 30C",
    mechanisms: ["Lever"],
    belt: "Black",
    beltLevel: "Black 5",
  },
  {
    id: "0b604114",
    name: "Yuema 750 series / Forte Enigma",
    mechanisms: ["Slider"],
    belt: "Black",
    beltLevel: "Black 5",
  },
  {
    id: "e35a3c91",
    name: "Bovii LOTO",
    version: "dimple lock",
    mechanisms: ["Dimple"],
    belt: "Unranked",
  },
];

const ownedLockIds = new Set([
  "07034c0f",
  "901b35b2",
  "2455f0ae",
  "40f7d7c7",
  "632f4069",
  "74a00ae3",
  "e1625c4d",
  "2ae1e0b8",
  "4f6bcdb7",
  "c6529d9c",
  "85d93eb1",
  "959a6b9d",
  "331c9d36",
  "fb5a9eb7",
  "c8259a23",
  "45e3cde7",
  "826c31e0",
  "b13f4b57",
  "d3ad5a73",
  "b8350901",
  "29ab2852",
  "2ae6a691",
  "104776ef",
  "aeaa6a09",
  "639c4f0b",
  "3335df97",
  "55053299",
  "ab1e901f",
  "e87f0ca2",
  "d974b48f",
  "efc01233",
  "5c0d870b",
  "ea1afad0",
  "55511995",
  "112d0034",
  "f133510b",
  "58307da0",
  "779e7dcb",
  "222bd1fa",
  "b8350900",
  "2484ce70",
  "9ec8706c",
  "171f76e9",
  "2ff8a738",
  "7168d463",
  "37951bc4",
  "9ca2c109",
  "e35a3c91",
  "a460c971",
  "1459e2c6",
  "bf8970de",
  "366d5f50",
  "5a6170fb",
  "06a28ac7",
  "d9e3829f",
  "506b242a",
  "35330d19",
  "3198fffc",
  "aee424c0",
  "0b604114",
  "cd0c2ff9",
  "3c73c705",
  "1d80c9bb",
  "a1233156",
  "5103e650",
  "562e964e",
  "13b06cba",
  "71833308",
  "f1e92541",
  "d08aa492",
  "dd764207",
  "111062fc",
  "814c5368",
  "0b82681f",
  "c942490e",
  "ea1d1d8c",
  "da09d849",
  "e4bb0668",
]);
const pickedLockIds = new Set([
  "07034c0f",
  "901b35b2",
  "2455f0ae",
  "40f7d7c7",
  "632f4069",
  "2ae1e0b8",
  "fb5a9eb7",
  "779e7dcb",
  "959a6b9d",
  "efc01233",
  "562e964e",
]);

export const locks: LockRecord[] = lockCatalog.map((lock) => ({
  ...lock,
  status: ownedLockIds.has(lock.id) ? "Owned" : "Wishlist",
  picked: pickedLockIds.has(lock.id),
}));

export const ownedLocks = locks.filter((lock) => lock.status === "Owned");
export const wishlistLocks = locks.filter((lock) => lock.status === "Wishlist");

export const beltCounts = Object.fromEntries(
  beltOrder.map((belt) => [belt, ownedLocks.filter((lock) => lock.belt === belt).length]),
) as Record<Belt, number>;

export const mechanismCounts = Object.entries(
  ownedLocks.reduce<Record<string, number>>((counts, lock) => {
    lock.mechanisms.forEach((mechanism) => {
      counts[mechanism] = (counts[mechanism] ?? 0) + 1;
    });
    return counts;
  }, {}),
)
  .map(([label, value]) => ({ label, value }))
  .sort((a, b) => b.value - a.value || a.label.localeCompare(b.label));

const brandFamilies = [
  "ASSA",
  "ABUS",
  "Master Lock",
  "Ruko",
  "Mul-T-Lock",
  "Schlage",
  "GOAL",
  "Burg Wächter",
  "Yale",
  "Lockwood",
  "Chubb",
  "FAB",
];

export const brandCounts = brandFamilies
  .map((label) => ({
    label,
    value: ownedLocks.filter((lock) => lock.name.includes(label)).length,
  }))
  .sort((a, b) => b.value - a.value || a.label.localeCompare(b.label));
